"""rename address

Revision ID: 57065ad917be
Revises: cbff0c888614
Create Date: 2025-06-13 18:41:42.635742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57065ad917be'
down_revision = 'cbff0c888614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
