"""add Department

Revision ID: 88754f0fc2d5
Revises: 1db41fefe7c9
Create Date: 2025-06-13 18:31:41.435835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88754f0fc2d5'
down_revision = '1db41fefe7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
